apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartKind: pages
    chartRepository: https://github.com/skreet2k/charts.git
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: Skreet2k
    repository: jx3_local
  - key: staging
    owner: Skreet2k
    repository: jx3_local
  - key: production
  ingress:
    domain: onebranch.dev
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: skreet2k
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
