apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - Skreet2k/jx3_local
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Skreet2k/jx3_local
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Skreet2k/backend
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Skreet2k/frontend
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Skreet2k/jx3-cluster
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Skreet2k/react-app
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Skreet2k/spring
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    external_plugins:
      Skreet2k/backend:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      Skreet2k/frontend:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      Skreet2k/jx3-cluster:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      Skreet2k/jx3_local:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      Skreet2k/react-app:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      Skreet2k/spring:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      Skreet2k/backend:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Skreet2k/frontend:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Skreet2k/jx3-cluster:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Skreet2k/jx3_local:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Skreet2k/react-app:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Skreet2k/spring:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - Skreet2k/jx3_local
      trusted_org: todo
    - repos:
      - Skreet2k/jx3_local
      trusted_org: todo
    - repos:
      - Skreet2k/backend
      trusted_org: todo
    - repos:
      - Skreet2k/frontend
      trusted_org: todo
    - repos:
      - Skreet2k/jx3-cluster
      trusted_org: todo
    - repos:
      - Skreet2k/react-app
      trusted_org: todo
    - repos:
      - Skreet2k/spring
      trusted_org: todo
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
