apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: Skreet2k
    provider: https://github.com
    providerKind: github
    repositories:
    - name: jx3-cluster
    scheduler: in-repo
  - owner: Skreet2k
    provider: https://github.com
    providerKind: github
    repositories:
    - name: react-app
    scheduler: in-repo
